import psycopg2

def parseEntry(line):
    line = line.replace('\n', '')
    item, desc = line.split(' : ')
    if '■・' in desc:
        desc2, examplesStr = desc.split('■・', 1)
        examples = examplesStr.split('◆')
    else:
        desc2 = desc
        examples = []
    if '◆' in desc2:
        desc3, note = desc2.split('◆', 1)
    else:
        desc3 = desc2
        note = ''

    return {'item': item, 'meaning': desc3, 'examples': examples, 'note': note}

def seed(entries):
    conn = psycopg2.connect('host=localhost dbname=english_school user=postgres')
    cur = conn.cursor()

    cur.execute('''
        DROP TABLE IF EXISTS dict; 

        CREATE TABLE dict (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            item TEXT NOT NULL, 
            meaning TEXT, 
            examples TEXT[], 
            note TEXT);
    ''')

    for entry in entries:
        cur.execute('INSERT INTO dict (item, meaning, examples, note) VALUES (%s, %s, %s, %s)', (entry['item'], entry['meaning'], entry['examples'], entry['note']))

    conn.commit()    



f = open("EIJIRO-1448.TXT", "r+", encoding="shift_jisx0213")

#lines = f.readlines()

lines = []
for i in range(10000):
    lines.append(f.readline())

entries = []

for line in lines:
    entries.append(parseEntry(line))

seed(entries)



'''
for i in range(50000,50100):
    print(entries[i])
'''

